name = "firstproof"
version = "0.1.0"
defaultTargets = ["Firstproof"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "6fc02d5eb4c2b0eb6a0bf08aa1d339f2b384389e"

[[lean_lib]]
name = "Firstproof"
